### ISSUE TITLE
setup.py should not import the thing it's installing

### ISSUE THREAD

**Issue by slinkp** [jeffknupp/sandman#11]
This creates major chicken-and-egg problems at install time. Works for you because you've already got all your dependencies...

```
[23:13:14]Pauls-MacBook-Air ~:(trunk)$ virtualenv --no-site-packages test2
New python executable in test2/bin/python
Installing setuptools............done.
Installing pip...............done.
[23:13:20]Pauls-MacBook-Air ~:(trunk)$ cd test2
[23:13:23]Pauls-MacBook-Air test2:$ source bin/activate
(test2)[23:13:26]Pauls-MacBook-Air test2:$ pip install sandman
Downloading/unpacking sandman
  Using download cache from /Users/pw/tmp/pip-download-cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Fs%2Fsandman%2Fsandman-0.4.0.tar.gz
  Running setup.py egg_info for package sandman
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/Users/pw/test2/build/sandman/setup.py", line 8, in <module>
        import sandman
      File "sandman/__init__.py", line 7, in <module>
        from flask import Flask
    ImportError: No module named flask
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/Users/pw/test2/build/sandman/setup.py", line 8, in <module>

    import sandman

  File "sandman/__init__.py", line 7, in <module>

    from flask import Flask

ImportError: No module named flask

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /Users/pw/test2/build/sandman
Storing complete log in /Users/pw/.pip/pip.log

```

**Comment by mehcode** [comment]
You should do some magic like this.

``` python
# ...
from os import path
from pkgutil import get_importer

base = path.abspath(path.dirname(__file__))
meta = get_importer(path.join(base, 'sandman')).find_module('meta').load_module('meta')

setup(
    # ...
    version=meta.version,
    # ...
)
```

Then the `__init__.py` can import `meta.py` and have `__version__` defined in there. That trick above is what's called a _direct_ import (it does not import any packages that are enroute thus preventing the chicken-and-egg problem).

**Comment by jeffknupp** [comment]
Argh, fixing this now. I knew about this when @audreyr mentioned it and just hadn't gotten around to fixing it yet.

**Comment by jeffknupp** [comment]
Ugh, I had written the function `find_version` a while ago but forgot to make the change to **use** it.

Fixed:

>    ~/c/g/sandman git:develop >>> mkvirtualenv -p /usr/bin/python2 clean                                         ✱
> Already using interpreter /usr/bin/python2
> New python executable in clean/bin/python2
> Also creating executable in clean/bin/python
> Installing setuptools............done.
> Installing pip...............done.
> (clean)~/c/g/sandman git:develop >>> pip install .                                                           ✱
> Unpacking /home/jeff/code/github_code/sandman
> Running setup.py egg_info for package from file:///home/jeff/code/github_code/sandman
> 
>   Downloading/unpacking Flask>=0.10.1 (from sandman==0.4.0)
>   Downloading Flask-0.10.1.tar.gz (544kB): 544kB downloaded
>   Running setup.py egg_info for package Flask
> 
> ```
> warning: no files found matching '*' under directory 'tests'
> warning: no previously-included files matching '*.pyc' found under directory 'docs'
> warning: no previously-included files matching '*.pyo' found under directory 'docs'
> warning: no previously-included files matching '*.pyc' found under directory 'tests'
> warning: no previously-included files matching '*.pyo' found under directory 'tests'
> warning: no previously-included files matching '*.pyc' found under directory 'examples'
> warning: no previously-included files matching '*.pyo' found under directory 'examples'
> no previously-included directories found matching 'docs/_build'
> no previously-included directories found matching 'docs/_themes/.git'
> ```
> 
> Downloading/unpacking Flask-SQLAlchemy>=1.0 (from sandman==0.4.0)
>   Downloading Flask-SQLAlchemy-1.0.tar.gz (92kB): 92kB downloaded
>   Running setup.py egg_info for package Flask-SQLAlchemy
> 
> ```
> warning: no previously-included files matching '*.pyc' found under directory 'docs'
> warning: no previously-included files matching '*.pyo' found under directory 'docs'
> no previously-included directories found matching 'docs/_build'
> no previously-included directories found matching 'docs/_themes/.git'
> ```
> 
> Downloading/unpacking SQLAlchemy==0.8.2 (from sandman==0.4.0)
>   Downloading SQLAlchemy-0.8.2.tar.gz (3.8MB): 3.8MB downloaded
>   Running setup.py egg_info for package SQLAlchemy
> 
> ```
> warning: no files found matching '*.jpg' under directory 'doc'
> no previously-included directories found matching 'doc/build/output'
> ```
> 
> Downloading/unpacking Werkzeug>=0.7 (from Flask>=0.10.1->sandman==0.4.0)
>   Downloading Werkzeug-0.9.4.tar.gz (1.1MB): 1.1MB downloaded
>   Running setup.py egg_info for package Werkzeug
> 
> ```
> warning: no files found matching '*' under directory 'werkzeug/debug/templates'
> warning: no files found matching '*' under directory 'tests'
> warning: no previously-included files matching '*.pyc' found under directory 'docs'
> warning: no previously-included files matching '*.pyo' found under directory 'docs'
> warning: no previously-included files matching '*.pyc' found under directory 'tests'
> warning: no previously-included files matching '*.pyo' found under directory 'tests'
> warning: no previously-included files matching '*.pyc' found under directory 'examples'
> warning: no previously-included files matching '*.pyo' found under directory 'examples'
> no previously-included directories found matching 'docs/_build'
> ```
> 
> Downloading/unpacking Jinja2>=2.4 (from Flask>=0.10.1->sandman==0.4.0)
>   Downloading Jinja2-2.7.1.tar.gz (377kB): 377kB downloaded
>   Running setup.py egg_info for package Jinja2
> 
> ```
> warning: no files found matching '*' under directory 'custom_fixers'
> warning: no previously-included files matching '*' found under directory 'docs/_build'
> warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
> warning: no previously-included files matching '*.pyc' found under directory 'docs'
> warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
> warning: no previously-included files matching '*.pyo' found under directory 'docs'
> ```
> 
> Downloading/unpacking itsdangerous>=0.21 (from Flask>=0.10.1->sandman==0.4.0)
>   Downloading itsdangerous-0.23.tar.gz (46kB): 46kB downloaded
>   Running setup.py egg_info for package itsdangerous
> 
> ```
> warning: no previously-included files matching '*' found under directory 'docs/_build'
> ```
> 
> Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/jeff/.virtualenvs/clean/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg (from Flask-SQLAlchemy>=1.0->sandman==0.4.0)
> Downloading/unpacking markupsafe (from Jinja2>=2.4->Flask>=0.10.1->sandman==0.4.0)
>   Downloading MarkupSafe-0.18.tar.gz
>   Running setup.py egg_info for package markupsafe
> 
> Installing collected packages: Flask, Flask-SQLAlchemy, SQLAlchemy, sandman, Werkzeug, Jinja2, itsdangerous, markupsafe
>   Running setup.py install for Flask
> 
> ```
> warning: no files found matching '*' under directory 'tests'
> warning: no previously-included files matching '*.pyc' found under directory 'docs'
> warning: no previously-included files matching '*.pyo' found under directory 'docs'
> warning: no previously-included files matching '*.pyc' found under directory 'tests'
> warning: no previously-included files matching '*.pyo' found under directory 'tests'
> warning: no previously-included files matching '*.pyc' found under directory 'examples'
> warning: no previously-included files matching '*.pyo' found under directory 'examples'
> no previously-included directories found matching 'docs/_build'
> no previously-included directories found matching 'docs/_themes/.git'
> ```
> 
>   Running setup.py install for Flask-SQLAlchemy
> 
> ```
> warning: no previously-included files matching '*.pyc' found under directory 'docs'
> warning: no previously-included files matching '*.pyo' found under directory 'docs'
> no previously-included directories found matching 'docs/_build'
> no previously-included directories found matching 'docs/_themes/.git'
> ```
> 
>   Running setup.py install for SQLAlchemy
>     building 'sqlalchemy.cprocessors' extension
>     gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -fPIC -I/usr/include/python2.7 -c lib/sqlalchemy/cextension/processors.c -o build/temp.linux-x86_64-2.7/lib/sqlalchemy/cextension/processors.o
>     gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro build/temp.linux-x86_64-2.7/lib/sqlalchemy/cextension/processors.o -L/usr/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/sqlalchemy/cprocessors.so
>     building 'sqlalchemy.cresultproxy' extension
>     gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -fPIC -I/usr/include/python2.7 -c lib/sqlalchemy/cextension/resultproxy.c -o build/temp.linux-x86_64-2.7/lib/sqlalchemy/cextension/resultproxy.o
>     gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro build/temp.linux-x86_64-2.7/lib/sqlalchemy/cextension/resultproxy.o -L/usr/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/sqlalchemy/cresultproxy.so
>     building 'sqlalchemy.cutils' extension
>     gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -fPIC -I/usr/include/python2.7 -c lib/sqlalchemy/cextension/utils.c -o build/temp.linux-x86_64-2.7/lib/sqlalchemy/cextension/utils.o
>     gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro build/temp.linux-x86_64-2.7/lib/sqlalchemy/cextension/utils.o -L/usr/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/sqlalchemy/cutils.so
> 
> ```
> warning: no files found matching '*.jpg' under directory 'doc'
> no previously-included directories found matching 'doc/build/output'
> ```
> 
>   Running setup.py install for sandman
> 
>   Running setup.py install for Werkzeug
> 
> ```
> warning: no files found matching '*' under directory 'werkzeug/debug/templates'
> warning: no files found matching '*' under directory 'tests'
> warning: no previously-included files matching '*.pyc' found under directory 'docs'
> warning: no previously-included files matching '*.pyo' found under directory 'docs'
> warning: no previously-included files matching '*.pyc' found under directory 'tests'
> warning: no previously-included files matching '*.pyo' found under directory 'tests'
> warning: no previously-included files matching '*.pyc' found under directory 'examples'
> warning: no previously-included files matching '*.pyo' found under directory 'examples'
> no previously-included directories found matching 'docs/_build'
> ```
> 
>   Running setup.py install for Jinja2
> 
> ```
> warning: no files found matching '*' under directory 'custom_fixers'
> warning: no previously-included files matching '*' found under directory 'docs/_build'
> warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
> warning: no previously-included files matching '*.pyc' found under directory 'docs'
> warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
> warning: no previously-included files matching '*.pyo' found under directory 'docs'
> ```
> 
>   Running setup.py install for itsdangerous
> 
> ```
> warning: no previously-included files matching '*' found under directory 'docs/_build'
> ```
> 
>   Running setup.py install for markupsafe
> 
> ```
> building 'markupsafe._speedups' extension
> gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -fPIC -I/usr/include/python2.7 -c markupsafe/_speedups.c -o build/temp.linux-x86_64-2.7/markupsafe/_speedups.o
> gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro build/temp.linux-x86_64-2.7/markupsafe/_speedups.o -L/usr/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/markupsafe/_speedups.so
> Successfully installed Flask Flask-SQLAlchemy SQLAlchemy sandman Werkzeug Jinja2 itsdangerous markupsafe
> Cleaning up...
> ```
