### ISSUE TITLE
Project abandoned or help needed?

### ISSUE THREAD

**Issue by MortalCatalyst** [jeffknupp/sandman#117]
Hi

I don't have the skill by myself currently to fix sandman issues, is the project abandoned as needing too much work or would a few key actions kickstart the project again.

Cheers

Sayth

**Comment by ir4y** [comment]
Hi @MortalCatalyst you can use new version https://github.com/jeffknupp/sandman2

**Comment by MortalCatalyst** [comment]
Thanks
