### ISSUE TITLE
Returning message NULL

### ISSUE THREAD

**Issue by eduardonunesp** [jeffknupp/sandman#13]
Everything seems to be alright (testing with a single table just like the tutorial at README) but when i call the the url a strange return;

curl localhost:5000/coupon

{
  "message": null
},

but when i run with admin access, the issue appeared:

sqlalchemy.exc.ArgumentError: status._ref_status and back-reference status._fk_status are both of the same direction <symbol 'ONETOMANY>.  Did you mean to set remote_side on the many-to-one side ?

This is a table, that have a reference to other table, and a self reference. So in Alchemy we need to set parameter remote_side, but how i do that in sandman ?

**Comment by jeffknupp** [comment]
I'll look into this (dynamically generating the SQLAlchemy references is a sore spot at the moment). Could you include your DB schema and the tables in question causing the issue?
