### ISSUE TITLE
admin-ui can not edit primary key

### ISSUE THREAD

**Issue by darengit** [jeffknupp/sandman#15]
We can get the admin-ui to display the primary key, however we can not edit it. Not sure if this is an appropriate issue or a "feature"

**Comment by jeffknupp** [comment]
It's done on purpose, though it certainly would be a pain for databases with poorly chosen primary keys. I'm working on a version of sandman that generates synthetic primary keys and keeps them in memory/pickle form so that _all_ primary keys are simple monotonically increasing integers.
