### ISSUE TITLE
Can't easily set BaseModelView.<some class field>

### ISSUE THREAD

**Issue by darengit** [jeffknupp/sandman#16]
There are a lot of class fields in BaseModelView that govern the behavior of the flask-admin. While using sandman its not straight forward how we can set any of BaseModelView's class fields. It would be great if we can do something like this:

""" assume a table called 'new_job' with primary key 'name' """

class new_job(Model):
    **tablename** = 'new_job'

class new_jobAdminView(ModelView):
    column_display_pk = True
    column_searchable_list = ('name')

register(new_job)
activate_admin_classes(new_jobAdminView)

**Comment by jeffknupp** [comment]
This was fixed a while ago. You can now use a custom admin class by setting the `__view__` attribute of your model.
