### ISSUE TITLE
Add script for simple startup

### ISSUE THREAD

**Issue by Tinche** [jeffknupp/sandman#18]
I'm thinking Sandman might be very interesting for integration testing at my work place.

Reading your docs, for very simple usage only a single piece of information is needed: the SQLAlchemy connection string. So why not bundle a simple CLI client (say, 'sandman') that would take a few parameters as command line args and eliminate all Python boilerplate, at least for simple use cases?

For example, I'd like to be able to install sandman and just do 

```
sandman postgresql://user:pass@localhost:5432/database
```

and have my database exposed for use by my test runner. Also interesting would be a parameter to have the server bind to other/all interfaces, instead of only localhost.

I might be persuaded to contribute this if you agree it would be useful. :)

**Comment by jeffknupp** [comment]
This is now possible using `sandmanctl URI`. It does exactly what you asked for and also goes so far as popping up a web browser pointing at the admin interface (though this can be turned off).

**Comment by Tinche** [comment]
Uhm I feel embarrased for having somehow missed this. Anyway, thanks!
