### ISSUE TITLE
Join condition for many  foreign key

### ISSUE THREAD

**Issue by ir4y** [jeffknupp/sandman#20]
I have relation at my database like this:

``` python
class Customer(Base):
    __tablename__ = 'customer'
    id = Column(Integer, primary_key=True)
    name = Column(String)

    billing_address_id = Column(Integer, ForeignKey("address.id"))
    shipping_address_id = Column(Integer, ForeignKey("address.id"))

  billing_address = relationship("Address", foreign_keys=[billing_address_id])
  shipping_address = relationship("Address", foreign_keys=[shipping_address_id])

class Address(Base):
    __tablename__ = 'address'
    id = Column(Integer, primary_key=True)
    street = Column(String)
    city = Column(String)
    state = Column(String)
```

When sandman try to create models from database, i get the error:
`sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables`

**Comment by jeffknupp** [comment]
If you want to use `sandman` with an existing SQLAlchemy database model, you'll have to derive from `sandman.model.Model` in your classes and use `sandman.model.db` to define `Column`, `ForeignKey`, `Integer`, etc. The following code worked perfectly fine for me:

``` python
from sandman.model import register, activate, Model
from sandman import db

class Customer(Model):
    __tablename__ = 'customer'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)

    billing_address_id = db.Column(db.Integer, db.ForeignKey("address.id"))
    shipping_address_id = db.Column(db.Integer, db.ForeignKey("address.id"))

    billing_address = db.relationship("Address", foreign_keys=[billing_address_id])
    shipping_address = db.relationship("Address", foreign_keys=[shipping_address_id])

class Address(Model):
    __tablename__ = 'address'
    id = db.Column(db.Integer, primary_key=True)
    street = db.Column(db.String)
    city = db.Column(db.String)
    state = db.Column(db.String)

register((Customer, Address))
activate(browser=False)
```

**Comment by ir4y** [comment]
I am not using SQLAlchemy.
I have a django project.
I create simple project for bug demonstration https://github.com/ir4y/customer_address

**Comment by jeffknupp** [comment]
Got it. This is a somewhat tricky problem to solve as there are multiple FKs to the same table, which is difficult for sandman to detect. As a temporary workaround, I've added a `admin(relationships=False)` option which will still give you the admin, just without all of the foreign key relationships represented.

In the long term, it would be nice for sandman to be able to handle this gracefully when automagically creating tables, but in the short term that's not likely.

Note that, of course, you could always just create the problematic sandman model classes yourself as was done above. This isn't as simple as just calling `activate()` but would still work fine.

**Comment by ntdunglc** [comment]
Do you have any plan to support it in near future? I think it's a must-have feature if you use relational databases. Most of the time you will need to manage relationships in your admin interface.

**Comment by jeffknupp** [comment]
I'm currently working on a fix for this. Note that it's possible to make
this work very easily if you're not dead-set on using sadmanctl. For
sandmanctl, I'm working on a way to specify that certain tables have
multiple foreign keys to the same table.
