### ISSUE TITLE
How to connect to mysql/postgres

### ISSUE THREAD

**Issue by dangayle** [jeffknupp/sandman#23]
Love this app, but the documentation isn't clear on how to connect to a db like MySQL or Postgres. I'm guessing I need to hunt through the code to find it?

**Comment by ir4y** [comment]
Sandman is using SQLAlchemy ORM.
So you can find all information what you need, at official  SQLAlchemy ORM documentation http://docs.sqlalchemy.org/en/latest/dialects/index.html.

Postgresql  example:

```
postgresql+psycopg2://user:password@host:port/dbname
```

using UNIX socket:

```
postgresql+psycopg2://user:password@/dbname?host=/var/run/postgresql
```

MySQL exmple:

```
mysql+mysqldb://user:password@host:port/dbname
```

**Comment by jeffknupp** [comment]
This is now in the `sandman` documentation as well, but @ir4y is correct that it simply requires an RFC-1738 style URI string
