### ISSUE TITLE
Always get "sqlalchemy.exc.AmbiguousForeignKeysError"

### ISSUE THREAD

**Issue by larsks** [jeffknupp/sandman#38]
I was excited to learn about Sandman and was hoping it would Just Work when pointed at the MySQL databases used by OpenStack.  Unfortunately, for every database I've tried I get:

> sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship floatingips.ports - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table.

**Comment by jeffknupp** [comment]
Working on this. It should be fixed in the next release.

**Comment by flazzarini** [comment]
As a workaround you could set 

``` python
app.config['SANDMAN_GENERATE_PKS'] = False
app.config['SANDMAN_SHOW_PKS'] = False
```

this worked for me.

**Comment by jeffknupp** [comment]
This is now fixed by setting `app.config['SANDMAN_GENERATE_PKS']` (as mentioned above) or using the `-g` flag with `sandmanctl`

**Comment by larsks** [comment]
I'm using commit `adecc6c4234f6ae3e0ece41ee44dec85a7e0104b`.  Running against an OpenStack Nova database (schema looks like [this](https://gist.github.com/larsks/8886189)], even with `-g` I get the same error:

```
$ sandmanctl  mysql://nova:secret@127.0.0.1/nova  --generate-pks
sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship security_group_rules.security_groups - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table.
```

**Comment by jeffknupp** [comment]
If you don't use sandmanctl, the following is possible via the following example code:

```
class Customer(Base):
__tablename__ = 'customer'
id = Column(Integer, primary_key=True)
name = Column(String)

billing_address_id = Column(Integer, ForeignKey("address.id"))
shipping_address_id = Column(Integer, ForeignKey("address.id"))

billing_address = relationship("Address", foreign_keys=[billing_address_id])
shipping_address = relationship("Address", foreign_keys=[shipping_address_id])
```

Note the use of `foreign_keys` there. I'm not sure that it's possible for `sandmanctl` to work this out on its own, since it would have to guess which of the available references to the table an individual relationship should use (i.e. `billing_address` in the example above can't automatically determine if it should use `billing_address_id` or `shipping_address_id`)

**Comment by jeffknupp** [comment]
FYI, I'm close to having this working for `sandmanctl`. I was wrong about not being able to determine the field for the relationship (since the table already exists, it's already associated with a field). Hopefully this will be fixed tomorrow. It will go out in the 0.8.0 release next week.
