### ISSUE TITLE
`RuntimeError: the session is unavailable` in Admin Interface

### ISSUE THREAD

**Issue by brutus** [jeffknupp/sandman#42]
I just downloaded and started up the servide with `sandmanctl` on  a local SQLite DB.

After adding to it with the _Save and Add_ (what's the difference to Submit?) throws me an `RuntimeError`:

```
RuntimeError: the session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
```

Full stacktrace here: https://gist.github.com/anonymous/5cf73c931c45dc73483f

**Comment by jeffknupp** [comment]
I've not seen sandmanctl complain about a secret key, but it's an easy
enough thing to fix.

**Comment by quinn** [comment]
I'm getting this error as well. What is the fix? Flask doc says to add `app.secret_key = 'super-secret-text'` but I'm not sure where I would add it.

**Comment by jeffknupp** [comment]
This should be fixed now. Please let me know if you are still seeing this error in the most updated version.
