### ISSUE TITLE
IOError running sandmanctl

### ISSUE THREAD

**Issue by larsks** [jeffknupp/sandman#44]
This is against aba5993.

I have sandman installed into a python virtualenv.

I ran sandmanctl against a local database:

```
sandmanctl --port=7070 mysql://USER:SECRET@127.0.0.1/keystone
```

This resulted in:

```
IOError: [Errno 20] Not a directory: '/home/lars/env/common/lib/python2.7/site-packages/sandman-0.7.4-py2.7.egg/sandman/templates/admin/index.html'
```

**Comment by larsks** [comment]
Note that sandman appears to be installed as zipped egg:

ls -l ~/env/common/lib/python2.7/site-packages/sandman-0.7.4-py2.7.egg 
-rw-rw-r--. 1 lkellogg lkellogg 2306210 Jan  9 16:08 /home/lars/env/common/lib/python2.7/site-packages/sandman-0.7.4-py2.7.egg

**Comment by larsks** [comment]
If I install sandman via:

```
easy_install --always-unzip .
```

It works correctly.

**Comment by jeffknupp** [comment]
Thanks for opening this. I fixed it by marking it non-`zip_safe` in the `setup.py` file.
