### ISSUE TITLE
Relative path creates an empty database

### ISSUE THREAD

**Issue by grimnight** [jeffknupp/sandman#46]
When using SQLite relative path creates an empty database in sandman directory in site-packages.

Running `sandmanctl "sqlite:///test.db"` in the same directory as `test.db` creates an empty database by that name in sandmans directory in site-packages.
Using the full path it works normally.

**Comment by ghost** [comment]
Can confirm, something that I would love to see fixed as well.

**Comment by jeffknupp** [comment]
As I mentioned in #34, you need to pass the full URI if you want to use a relative path, i.e. you need to add '+pysqlite' after the 'sqlite' portion. Final result should be `sandmanctl "sqlite+pysqlite:///test.db"`
