### ISSUE TITLE
skip tables with missing primary keys

### ISSUE THREAD

**Issue by rbonthond** [jeffknupp/sandman#47]
looks like sqlalchemy doesn't work with tables without a primary key:
sqlalchemy.exc.ArgumentError: Mapper Mapper|sap_zpp_bom_report|sap_zpp_bom_report could not assemble any primary key columns for mapped table 'sap_zpp_bom_report'

using:
sandman==0.7.5
SQLAlchemy==0.9.1
Flask-SQLAlchemy==1.0

**Comment by quinn** [comment]
this will cause it to fail on all Ruby on Rails databases because of schema_migrations

**Comment by jeffknupp** [comment]
Note that `sandmanctl` has an option to _generate_ primary keys for tables without them (by using a union of all columns). That should take care of this issue.

**Comment by quinn** [comment]
Thanks for the tip, that worked for me!

**Comment by rbonthond** [comment]
worked for me to!

**Comment by barraponto** [comment]
@jeffknupp can't primary key generation be a default option? right now it errors out and leaves users clueless on what to do about tables without primary keys.

BTW, it will fail on most drupal databases because of this.
