### ISSUE TITLE
Support authentication

### ISSUE THREAD

**Issue by jeffknupp** [jeffknupp/sandman#5]
Support various means of authentication, starting with simple HTTP authentication

**Comment by doesntwork** [comment]
what does it mean by ready? can we see how to get this working?

**Comment by svenstaro** [comment]
What's the status on this? Will you push auth soon or do I need to roll my own? Would greatly appreciate an estimate so that I know whether waiting would be useful or not. :)

**Comment by jeffknupp** [comment]
This is now complete. HTTP Basic Authentication is now fully supported after the latest set of commits.

**Comment by jeffknupp** [comment]
Sorry about the late reply. In case you hadn't seen the notificaiton,
authorization (HTTP Basic Auth) is now supported. Token-based
authentication is coming soon (and I'm being purposefully nebulous about
when :) ).

Cheers,
Jeff
