### ISSUE TITLE
can sandman work with one table and build nested routes?

### ISSUE THREAD

**Issue by doesntwork** [jeffknupp/sandman#50]
for example I have one table as so. I would like to build a tree out of it and store it in sandman so that it can give me routes like 

```
cat1/subcats/subcats/data, cat3/subcats/data
```

the table

```
cat1|subcat|subcat|data
cat1|subcat2|subcat|data
cat2|subcat|data
cat3|subcat|data
cat3|subcat2|data
cat3|subcat3|data
```

any suggestions would be great.

**Comment by jeffknupp** [comment]
If you have the proper relationships in your database, theoretically this should work. Foreign keys can be referenced (along with all other attributes) using the style of route that you mentioned. I'd be interested to see if this works.

As an aside, `sandman` is primarily concerned with creating REST APIs for existing databases. If you're starting from scratch, there might be tools out there that are easier to use than `sandman`.
