### ISSUE TITLE
Does not work with Subclasses

### ISSUE THREAD

**Issue by bfcondon** [jeffknupp/sandman#51]
I have an existing Flask app that subclasses Model.  I have modified it to use sandman.

class Foo(Model):

class Bar(Foo):

but I receive an error at the second class definition.

sqlalchemy.exc.InvalidRequestError: Table 'foo' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.

This works fine in my regular Flask app, so I think it may be a bug with sandman.

**Comment by jeffknupp** [comment]
Did you give `Bar` a different `__tablename__` attribute? Otherwise it will try to bind to the `foo` table, which `Foo` has already done.

**Comment by bfcondon** [comment]
You are right, I am using single table inheritance, so I was not defining a `__tablename__` attribute for Bar.

**Comment by jeffknupp** [comment]
Allright. Closing this now, but will add a note in the documentation.
