### ISSUE TITLE
Errors on adding tables without primary keys.

### ISSUE THREAD

**Issue by sp1d3rx** [jeffknupp/sandman#56]
If any tables do not have a primary key, there is an error generated when trying to launch via sandmanctrl.

**Comment by jeffknupp** [comment]
This is a duplicate of a number of tickets ( #31 for example). You need to pass the correct command line flags to `sandmanctl` to make it work around the issue, specifically `sandmanctl -g` to have `sandmanctl` generate primary keys by using a union of all columns.
