### ISSUE TITLE
tries to launch a web browser for 0.0.0.0 instead of localhost

### ISSUE THREAD

**Issue by sp1d3rx** [jeffknupp/sandman#57]
If no hostname is specified on the command line, the default web browser pops up with http://0.0.0.0:5000/admin when it should be going to http://localhost:5000/admin

**Comment by jeffknupp** [comment]
Going to 0.0.0.0 is an intended feature as it allows systems outside of `localhost` to see sandman. Is opening this address causing an issue in some browser (it resolves to `localhost` in Chrome)?

**Comment by sp1d3rx** [comment]
Chrome (on Windows) gives Error code: ERR_ADDRESS_INVALID

**Comment by jeffknupp** [comment]
Are you using the most up to date version of sandman? In dev it's opening 127.0.0.1.

**Comment by jeffknupp** [comment]
Actually, it _is_ opening 0.0.0.0. Fixing.
