### ISSUE TITLE
Option to generate models for all schema namespaces

### ISSUE THREAD

**Issue by pau** [jeffknupp/sandman#58]
It looks like sandman only generates models for tables that are using the default schema. I use different schemas to create a logical groupings of my tables.

I hacked on a feature that adds an --all-schemas option to sandmanctl so that it generates models for all my schemas: 358bbd3cedeb1ea0798d2bb5ae796565ab26dc89

Let me know your thoughts or if you already have other plans for handling multiple schemas.

I'll gladly write tests if you are interested in merging this. Thanks!

**Comment by jeffknupp** [comment]
I'd definitely be interested in merging this if you are able to write some
tests for it. And thanks for replacing the stupid way I was checking config
variables with the proper way...

**Comment by pau** [comment]
Cool. I'll create some tests for it, I'll have some time next weekend. Will send a pull request when I'm done.

**Comment by tsemerad** [comment]
Has this feature been implemented? I tried searching the repository for all-schemas, but couldn't find it.
