### ISSUE TITLE
AmbiguousForeignKeysError

### ISSUE THREAD

**Issue by jacobsvante** [jeffknupp/sandman#59]
[This error](https://gist.github.com/jmagnusson/8932939) seems to come up with `sandmanctl` when there are multiple foreign keys pointing to the same table. I haven't looked into the issue enough yet to know how hard it would be to add support for this, but perhaps an option could be added to ignore such columns?

**Comment by jeffknupp** [comment]
I thought this issue had been resolved. Checking into it.

**Comment by bkcsfi** [comment]
I have encountered this error also with 0.7.7rc3, after deleting the troublesome tables encountered in #65 (test db only), I get:

sqlalchemy.exc.AmbiguousForeignKeysError

reading the sqla docs, I think the best fix for this might be related to #60, allow users to partially  or fully declare the sqla mapping.

being lazy, I'd like to use automap in sandman and then I'd only need to declare the naming of the relationships between tables where there are multiple fk links.

**Comment by areski** [comment]
Getting similar error with a django project "sqlalchemy.exc.AmbiguousForeignKeysError: Could not determine join condition between parent/child tables on relationship notification_notice.auth_user - there are multiple foreign key paths linking the tables.  Specify the 'foreign_keys' argument, providing a list of those columns which should be counted as containing a foreign key reference to the parent table."

**Comment by jeffknupp** [comment]
Multiple foreign keys to the same table are now supported.

**Comment by areski** [comment]
Thanks for the fix!
