### ISSUE TITLE
Use existing declarative definitions

### ISSUE THREAD

**Issue by jacobsvante** [jeffknupp/sandman#60]
Would it be possible to use the `register` function on existing plain SQLAlchemy declarative classes? Perhaps one could check if the passed in model has the `__endpoint__` attribute and if not add `sandman` defaults to it. I don't really know if this is feasible, but it would be nice to not have to redeclare your models.

**Comment by jeffknupp** [comment]
Sure, I think this could be done. I'll prioritize this request along with
other feature requests.
