### ISSUE TITLE
Retrieval of nested resources still produces string rep of class

### ISSUE THREAD

**Issue by synthsym** [jeffknupp/sandman#64]
The change in 1dc11f3fb89399775e76fd082b300182004361a4 doesn't seem to be working on my PostgreSQL database. I still get a string rep of the SQLAlchemy class like so: `<flask_sqlalchemy.subtopics object at 0x235a150>`. I definitely have the latest commit from the `develop` branch, and the tests seem to work for the sample DB, so i'm really confused as to what's wrong.

**Comment by jeffknupp** [comment]
Sorry, I had misunderstood your earlier issue. I'm assuming this is the functionality you were looking for.
