### ISSUE TITLE
Content-type: application/x-www-form-urlencoded; charset=UTF-8; not supported

### ISSUE THREAD

**Issue by skunkwerk** [jeffknupp/sandman#67]
I'd like to add this content type to the HTML_CONTENT_TYPES in sandman/sandman.py, as some REST clients like Retrofit use this.
In addition, the error message seems to have the supported and unsupported content types switched around, on lines 22-24:
UNSUPPORTED_CONTENT_TYPE_MESSAGE = """Content-type [{}] not supported.
  Supported values for 'Content-type': {}""".format(str(ACCEPTABLE_CONTENT_TYPES), '{}')

I think it should be:
'{}', str(ACCEPTABLE_CONTENT_TYPES))

I have a bug fix ready, but need further testing.

**Comment by jeffknupp** [comment]
This should work now.
