### ISSUE TITLE
Consider merging with armet

### ISSUE THREAD

**Issue by mehcode** [jeffknupp/sandman#7]
This looks like a great project you have here @jeffknupp.

I'd like you to take a look at https://github.com/armet/python-armet and for you to consider merging our efforts.

There isn't a lot of documentation for it at the moment (looking to rectify that very shortly) but here is the general idea. Armet is a RESTful abstraction framework that plugs in to _anything_ (eg. django, tornado, sqlalchemy, bottle, flask, etc.). A basic example below. We've got a good bit of features like  authentication, authorization, advanced filtering, etc.

``` python
from armet import resources
from . import models, app

@armet.route('/', app)
class Album(resources.ModelResource):
    class Meta:
        connectors = {'http': 'flask', 'model': 'sqlalchemy'}
        model = models.Album
        slug = resources.IntegerAttribute('id')

    id = resources.IntegerAttribute('id')
    name = resources.TextAttribute('name')
```

That would allow a various requests to `/album` (eg. `POST`, `PUT`, `OPTIONS`, etc.)

Something you're doing currently that I've had plans to add to armet is the attribute detection.

---

Both of our projects are still fairly new and malleable so what I am proposing is we work together to add all the features from sandman you'd want, closing sandman, and then jointly maintaining armet (the primary reason for sandman into armet is that armet has the connector structure in-place to support most frameworks) and making it the best possible RESTful framework we can.

What do you think?

**Comment by mehcode** [comment]
@jeffknupp Have you found time to review my proposal? I'm only asking because I see your recent activity on things like https://github.com/jeffknupp/sandman/issues/8 and want you to know that we can already have solutions for that.

I'm not trying for conflict or a superiority contest of whose library is better here. I'm just trying to build the best REST API framework possible and I see that you have some good things here and instead of us going our separate ways it just makes sense for us to work together.

**Comment by jeffknupp** [comment]
Sorry for the late reply, I missed this originally. While I appreciate your offer to merge, I think our projects really focus on two different things. It seems that `armet` is focused on building a RESTful API from scratch, while `sandman` is wholeheartedly devoted to creating a RESTful service for **existing** databases.

The idea is that, especially in the enterprise, there are databases that you're not able to change the structure of but which you'd like to create a REST API for. Doing so in every other framework I've seen requires reverse-engineering that framework's Model abstraction from your _existing_ database. `sandman` tries to give you as much functionality as possible out of the box without the overhead of writing boilerplate, which makes many would-be projects a non-starter.

Regardless, I'm enjoying the work on it and learning a good deal, so I'd continue the project even if we did merge. That being said, free to use any of my introspection code as you please.

**Comment by mehcode** [comment]
@jeffknupp Database introspection would be something awesome to add to armet. I love the idea. It could be implemented as a type of of model that gets passed into the a model resource (so that it still gets all the benefits including auth, filtering, pagination, etc.).

``` python
from armet import resources, models

class Album(models.IntrospectedModel):
    class Meta:
        table = 'album'

class AlbumResource(resources.ModelResource):
    class Meta:
        model = Album
```

The thing is that **database introspection to build REST APIs** and **building REST APIs** are so close that there is a ton of overlap of functionality (the actual API, authentication, authorization, etc, etc.) and it would be a shame to have the functionality re-implemented in two different projects. 

Something else we could do is keep sandman and rewrite it on top of armet so that the project is still separate and its just adding database introspection to armet.

Let me know what you want to do.

**Comment by battlesnake** [comment]
Split the introspection into a separate module, everybody wins...    including my own http://github.com/battlesnake/node-mysql-orm :smile:
