### ISSUE TITLE
How to use sandman in another Flask application?

### ISSUE THREAD

**Issue by svenstaro** [jeffknupp/sandman#70]
I would essentially like to only use sandman as a blueprint and register it to somewhere. I would like to be able to register admin and api to different prefix, preferably. This should be fairly easy to do.

**Comment by svenstaro** [comment]
Ok I solved this (though the solution gets only 3 out of 5 stars, IMO) by essentially combining both applications using the DispatcherMiddleware like so:

```
from flask import Flask
from werkzeug.wsgi import DispatcherMiddleware
from sandman import app as sandman_app

from myapp.core import db

def create_app():
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object('myapp.config')

    db.init_app(app)

    from myapp.main.views import main
    app.register_blueprint(main)

    sandman_app.config = app.config
    from sandman.model import activate
    activate(browser=False)
    app.wsgi_app = DispatcherMiddleware(app.wsgi_app, {'/api': sandman_app.wsgi_app})
    return app
```

It works fairly wonderfully though I'm uncertain about the cleanliness of it and whether it could have any unforeseen consequences. If so, please enlighten me. This stuff should perhaps go to the docs somewhere.

Docs on this: http://flask.pocoo.org/docs/patterns/appdispatch/ and http://flask.pocoo.org/docs/patterns/appfactories/

**Comment by jeffknupp** [comment]
This does indeed seem to be the canonical approach to using multiple application objects in a single interpreter. I'll update the docs to reflect this.
