### ISSUE TITLE
Win7 install error

### ISSUE THREAD

**Issue by balagod** [jeffknupp/sandman#77]
System config:
win7 , python-2.7.6, sandman-0.7.4

Error details:
c:\sandman-0.7.4> python setup.py install
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    version=find_version('sandman', '**init**.py'),
  File "setup.py", line 16, in find_version
    version_file = read(*file_paths)
  File "setup.py", line 13, in read
    return codecs.open(os.path.join(here, *parts), 'r').read()
  File "c:\Python27\lib\codecs.py", line 881, in open
    file = **builtin**.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'c:\sandman-0.7.4\sandman\**init**.py'

**Comment by phillipsj** [comment]
Any reason you are not using PIP to install?

**Comment by balagod** [comment]
The problem is python installed inside program files folder as a standard user not able to write there. I did same on admin user with pip. It solved☺
