### ISSUE TITLE
Make "resources" key configurable.

### ISSUE THREAD

**Issue by aczapszys** [jeffknupp/sandman#81]
I'd like the JSON result lists to be labeled with the table name.  Currently, it always uses the word "resources".

```
Ex: GET /customers?last_name=Smith
{
  "customers": [ .. ]
}
```

Can this word be configurable?

**Comment by jeffknupp** [comment]
This is now available after commit 8d28744e38b680f01050f4967537fad6a0569017. Just set the `__top_level_json_name__` to whatever you'd like.
