### ISSUE TITLE
(PostgreSQL) Unable to discover tables under non-public schemas

### ISSUE THREAD

**Issue by yawboakye** [jeffknupp/sandman#93]
All my database tables, except `play_evolutions` are not under the `public` schema. And even though I've added the various schemas to my database's search path (via `ALTER DATABASE database_name SET search_path TO "..."`) sandman is still unable to discover them.

**Comment by KurtJansson** [comment]
Had the same problem, but changing the search path helped (via `ALTER USER <user> SET search_path = <schema>;`).

Before that, I tried to set the schema in my code via `__table_args__ = {'schema': '<schema>'}`, but sandman was still unable to find the table (_"sqlalchemy.exc.NoSuchTableError"_).

Anyway, I would expect sandman to discover all the tables out of the box.
